// vite-react/src/components/LineChart/LineChart.tsx
// import React from "react";
import { useEffect } from "react";
import Chart from "react-apexcharts";

import { LineChartProps } from ".";

const LineChart = <T,>({ className, ...props }: LineChartProps<T>) => {
  useEffect(() => console.log("LineChart is rendered"));
  return (
    <div className={className}>
      <Chart {...props} type="line" />
    </div>
  );
};

LineChart.defaultProps = {
  options: {},
  series: [{ name: "", data: [] }],
  className: "",
};

export default LineChart;

// vite-svelte/src/components/LineChart/LineChart.svelte
<script lang="ts">
import { chart } from "svelte-apexcharts";
import type { LineChartSeries } from ".";

export let series: LineChartSeries<number>| undefined = { name: "", data: [] }
export let className: string = ''

$: options = {
  chart: {
    type: "line",
  },
  series: [series],
};
$: console.log('LineChart is rendered')
</script>

<div class={className}>
  <div use:chart={options} />
</div>
