// vite-svelte/vite-svelte/src/components/LineChart/LineChart.svelte
<script lang="ts" generic="T" >
import Chart from "svelte-apexcharts";
import { LineChartProps } from ".";

export let props= { //: LineChartProps<T>  = {
  options: {},
  series: [{ name: "", data: [] }],
  className: "",
}
</script>

<div class={$$props.className}>
  <Chart series={props.series} options={props.options} type="line" />
</div>

// vite-react/src/components/LineChart/LineChart.tsx
// import React from "react";
import Chart from "react-apexcharts";

import { LineChartProps } from ".";

const LineChart = <T,>({ className, ...props }: LineChartProps<T>) => (
  <div className={className}>
    <Chart {...props} type="line" />
  </div>
);

LineChart.defaultProps = {
  options: {},
  series: [{ name: "", data: [] }],
  className: "",
};

export default LineChart;
